### ISSUE TITLE
Chose between BSD or GPL

### ISSUE THREAD

**Issue by sinistag** [AIR-EISTI/Market_Manager_V2#1]
The readme says the project is under BSD licence, but the LICENCE file contains GPL.

We should choose one and keep it. (I think BSD is more appropriate)

**Comment by DracarysBZH** [comment]
BSD 2-Clause License
or 
BSD 3-Clause License

**Comment by tjiho** [comment]
with Gpl, the source code will be reuse just for open-sources projects, that's a good thing !

**Comment by sinistag** [comment]
GPL is not free.

If people want to use it in a larger private project, they will be able to, as long as they quote us, with BSD.

For the same reason, I'd say we should use BSD 2-Clause rather than the 3-Clause. But I think it's you who should choice @DracarysBZH

**Comment by DracarysBZH** [comment]
So, I read the different license and actually I prefere the BSD 2-Clause. 

I will change it as soon as possible.
