### ISSUE TITLE
Is the use of cookies instead of localStorage justified ?

### ISSUE THREAD

**Issue by hannaeko** [AIR-EISTI/Market_Manager_V2#4]
Hey,
If I didn't miss anything, you are using cookies just as storage on the client side. Even if that works as expected I think there are some drawbacks.   
First as the access to cookies is not well supported in JavaScript you need to load an additional library. Also the cookies are sent within each request and if there are not used server-side it is a bit of a shame to have such an overhead.  

I know that it will not impact a lot the perfermance but is it not more appropriate to use some kind of client-side only storage like [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) or [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) ?

**Comment by DracarysBZH** [comment]
Hey,
In fact I didn't know this solution. But yes it's more appropriate so I will implement It asap.
